spring.application.name=phoenix-bakery-backend

server.port=8080

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=VHvqnsRwzDWGvGqxQzBScaFxyRAKKtVr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,https://pbe-lead-management.vercel.app